name: Deploy code and infra

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      git_ref:
        required: true
        type: string
        
        
env:
  ENVIRONMENT: ${{ inputs.environment }}
 
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is deploying to the ${{ inputs.environment }} environment"
      - name: Create Prod Release
         if: inputs.environment == 'prod' && success()
         uses: tubone24/update_release@v1.0
         env:
           GITHUB_TOKEN: ${{ github.token }}
           TAG_NAME: ${{ inputs.git_ref }}
         with:
           prerelease: false
