name: Initiate release to prod
on:
  push:
    tags:
      - 'v*'
      
env:
  ENVIRONMENT: prod
jobs:
  deploy-app-prod:
    runs-on: ubuntu-latest
    environment: $ENVIRONMENT
    steps:
      - run: echo "This is deploying to the ${{ env.ENVIRONMENT}} environment"
  prep-prod-release:
    runs-on: ubuntu-latest
    environment: ${{ env.ENVIRONMENT}}
    steps:
      - run: echo "This job only run in the prod $ENVIRONMENT environment and will trigger the $ENVIRONMENT deploy. tag ${{ github.ref }}"
      - name: Create Prod Release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref }}
        with:
          prerelease: false
