name: Initiate release to prod
on:
  workflow_run:
    workflows: ["stg deploy"]
    types:
      - completed
jobs:
  deploy-app-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "This is deploying to the prod environment"
  prep-prod-release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "This job only run in the prod env environment and will trigger the prod deploy."
      - name: Create Prod Release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ github.ref }}
        with:
          prerelease: false
