name: Initiate release to prod
on:
  workflow_run:
    workflows: ["stg deploy"]
    types:
      - completed
jobs:
  deploy-app-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "This is deploying to the prod environment"
