name: stg deploy
on:
  release:
    types: [prereleased]
    
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "This is deploying to the stf environment with the github ref of ${{ inputs.git_ref }}"
  prep-prod-release:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "This job only run in the prod env environment and will trigger the prod deploy."
      - name: Create Prod Release
        uses: tubone24/update_release@v1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG_NAME: '${{ github.ref }}'
        with:
          prerelease: false
