name: stg deploy
on:
  release:
    types: [prereleased]
    
env:
  ENVIRONMENT: stg
    
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - run: echo "This is deploying to the stg environment with the github tag ${{ github.ref }}"
