name: stg deploy
on:
  release:
    types: [prereleased]
    
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - run: echo "This is deploying to the stf environment with the github ref of ${{ inputs.git_ref }}"
