name: Deployment
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      git_ref:
        required: true
        type: string

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
          environment: ${{ github.environment }}

  start-deployment:
    needs: cancel-previous-runs
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Stage Release
        if: inputs.environment == 'stg' && success()
        uses: ./.github/workflows/cd-stg.yml
          with:
            environment: ${{ github.environment }}
      - name: Create Prod Release
        if: inputs.environment == 'prod' && success()
        uses: ./.github/workflows/cd-prod.yml
          with:
            git_ref: ${{ inputs.git_ref }}
            environment: ${{ github.environment }}
